link_ror: "https://www.railstutorial.org/"
link_author: "https://www.michaelhartl.com/"
link_contact:  "https://www.railstutorial.org/contact"
link_help: "https://www.railstutorial.org/help"
link_book: "https://www.railstutorial.org/book"
